runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /templates
  script: templates
- url: /video
  script: video
- url: /style_dir
  static_dir: style_dir
- url: /images
  static_dir: images
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
