runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /templates
  script: templates
- url: /style_dir
  script: style_dir
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
